# This workflow will create and push images to DockerHub

name: Push images to DockerHub

# Controls when the action will run. Triggers the workflow when a release is published.
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Setup Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Runs a set of commands using the runners shell
    - name: Build the images
      run: python3 scripts/build_images.py
    
    # Logs in to DockerHub
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:    
        username: arterysinferencesdk
        password: ${{ secrets.ARTERYSINFERENCESDK_DOCKER_HUB_PASSWORD }}

    # Pushes the images to the registry
    - name: Push the images to the registry
      run: ./scripts/push_images.sh
